### ISSUE TITLE
Can't open on chrome

### ISSUE THREAD

**Issue by xxKeoxx** [ady624/webCoRE#1]
I am trying to send the url from my iphone to my Mac and I get this message

> Oops, you are not logged in!
> 
> Please open the SmartThings IDE, go to Live Logging, then open the SmartThings CoRE app and look for the dashboard URL in the Live Logging page. You will need to open that link for the first time.

If I follow these instructions my log view for webCoRE is blank.

**Comment by ady624** [comment]
Please enable logging in the ST app's Settings. I have updated the message to inform on the requirement of Logging being enabled. Thank you
