### ISSUE TITLE
Timers with a preset "At this time", the offset does not allow for expressions

### ISSUE THREAD

**Issue by ericvitale** [ady624/webCoRE#12]
Use case: Looking to provided a random offset. For example:

( -15 + random( 30 ) ) minutes after sunrise

![image](https://cloud.githubusercontent.com/assets/8474048/26585757/1b688058-451b-11e7-888a-8e8d8181fe92.png)

**Comment by ady624** [comment]
Added, please test. Thank you.

**Comment by ericvitale** [comment]
Should this... give me +/- or is that a UI issue?

![image](https://user-images.githubusercontent.com/8474048/26891789-3d17fc00-4b84-11e7-9534-2c37ec7064ba.png)

![image](https://user-images.githubusercontent.com/8474048/26891799-451ddc80-4b84-11e7-8f00-33ea95546804.png)
