### ISSUE TITLE
Support Event Subscriptions on Global Variables

### ISSUE THREAD

**Issue by andrewmunsell** [ady624/webCoRE#17]
Right now, local variables with devices will create subscriptions correctly. However, global variables do not create subscriptions properly despite showing the lightning bolt icon.

Note how the lightning icon is present in the code view, but the yellow warning is still present and the list of subscriptions is empty.

<img width="1184" src="https://user-images.githubusercontent.com/357386/27747572-9ae8f54c-5d80-11e7-992c-320807335c2e.png">

**Comment by gustvao** [comment]
+1 here.. looking forward to this feature

**Comment by ady624** [comment]
Please test out v0.2.0e5.20170812 - BETA M2 - Allowing global variables create device subscriptions (due to demand)
