### ISSUE TITLE
Request: Add variable to reflect SHM intrusion status

### ISSUE THREAD

**Issue by green-arrow** [ady624/webCoRE#18]
I think that having a variable that can be observed / listened to that tells whether SHM has detected an intrusion / had the intrusion dismissed would be very useful.

One of my use cases is turning on interior cameras when an intrusion is detected during 'Armed/Stay', then turning them off once the intrusion is dismissed.

I can look into adding this if you're interested / can point me in the right direction.

**Comment by green-arrow** [comment]
Update: it looks like this should be pretty straightforward, adding the variable to `getSystemVariables` and `getSystemVariableValue` with a value of `return (location.incidents != null && location.incidents.length > 0) ? true : false;`

Am I missing anything else that would need to be done? Also, if you're interested in this, what would you think of `shmIncidentDetected` as a variable name?

Thanks in advance for taking the time to read / consider this 😄

**Comment by ady624** [comment]
Added in 0d2 I think

$shmTripped true or false
$incidents list of incidents - read $incidents.length and then $incidents[0], etc.

**Comment by green-arrow** [comment]
@ady624 will this require polling in the piston or is it a monitored variable?

**Comment by ady624** [comment]
There are no visible events, unfortunately, so a loop for polling is required. Maybe every 5 minutes or so?

**Comment by green-arrow** [comment]
Awesome, thanks for this!
