### ISSUE TITLE
How to implement a tri-state switch?

### ISSUE THREAD

**Issue by ScottChapman** [ady624/webCoRE#27]
So, I am getting up to speed on WebCoRE. What I am trying to do is create a tri-state switch for controlling my HVAC states (Cooling, Heating, off).

I thought I would create 3 virtual switches for each state, and when one is turned on it will turn off the others.

What I am not sure about how to do is can the actuating switch set the state of the other switches WITHOUT triggering the piston for that switch?

Does that make sense?

**Comment by ScottChapman** [comment]
I ended up implementing this myself, wasn;t hard actually. Used a global variable to control whether pistons should perform actions or just change state.

**Comment by MikeBishop** [comment]
I know you implemented it a different way long since, but I would implement this by having no actions on a switch turning off.  I would trigger actions on any switch turning on (which would include turning off the other switches), and then on all switches being turned off.)
