### ISSUE TITLE
Error greater than or equal to

### ISSUE THREAD

**Issue by tonesto7** [ady624/webCoRE#3]
I realize you are still in alpha.  I just wanted to let you know of issue i was seeing in testing.
Error calling comparison comp_stays_greater_than_or_equal_to: groovy.lang.MissingMethodException: No signature of method: script1491876398496636377990.comp_stays_greater_than_or_equal_to() is applicable for argument types: (java.util.LinkedHashMap, java.util.LinkedHashMap, java.util.LinkedHashMap) values: [[logging:[error:true, warn:true, info:true, ...], ...], ...]

**Comment by ady624** [comment]
the internal functions for stays or any one of combinations do not yet exist, hence the error. It's not a bug, it's a missing piece altogether.
