### ISSUE TITLE
Using plus in expression in combination with a sensor value doesn't work

### ISSUE THREAD

**Issue by c7pher** [ady624/webCoRE#32]
case:
[Weatherstation : dewpoint] + 1 (with dewpoint set to 13) = 131

using a double negative works:
[Weatherstation : dewpoint] - (-1) = 14

Also dividing and multiplying work as intended.

![screenshot 2017-10-26 at 00 54 29](https://user-images.githubusercontent.com/32451309/32027252-54385d26-b9e8-11e7-97ee-f9bfb615f40e.png)

![screenshot 2017-10-26 at 00 55 39](https://user-images.githubusercontent.com/32451309/32027288-7ffa5572-b9e8-11e7-881f-17d6e9703131.png)

**Comment by c7pher** [comment]
using the offset 1 as a variable is ignored completly, either wich calculation I try

**Comment by idpaterson** [comment]
That value might be coming out of your device handler as a string. One way to handle that is to use `int([Weatherstation : dewpoint]) + 1` to convert it to a number.

**Comment by c7pher** [comment]
confirmed working
