### ISSUE TITLE
Executing a piston from a global variable subscription

### ISSUE THREAD

**Issue by disforw** [ady624/webCoRE#35]
Since v0.2.0fb, pistons can no longer execute from a global variable. I have documented this issue in the forum which includes a test piston, and the resulting logs.
https://community.webcore.co/t/last-update-broke-global-variable-subscription/2143

**Comment by disforw** [comment]
A temporary fix to this problem has been found by @ipaterson in the following thread, post #3.
https://community.webcore.co/t/last-update-broke-global-variable-subscription/2143/3

**Comment by idpaterson** [comment]
Thanks for reporting, this should be fixed in v0.2.0fe.20171109.

The addition of superglobals (spans multiple webCoRE installs for the same location) changed the event name for normal globals and `on events from` was filtering out events based on the prior name.
