### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by RobinWinbourne** [ady624/webCoRE#5]
MPEG snapshot to MMS

**Comment by ianisms** [comment]
String indexof(text)
String replace - support regex in search and replace text

**Comment by ady624** [comment]
What do you mean by MPEG spanshot to MMS?

**Comment by RobinWinbourne** [comment]
Video snapshot to picture message (MMS).

**Comment by ady624** [comment]
I am not sure ST supports MMS? Maybe another provider?

Closing this :D
