### ISSUE TITLE
three axis for smart things contact sensor JSON error

### ISSUE THREAD

**Issue by staticxsoil** [ady624/webCoRE#58]
This week my garage door sensor based pistons stopped working. It looks like there is a json error happening. the error is:
An error occurred while executing the event: groovy.json.JsonException: A JSON payload should start with an openning curly brace '{' or an openning square bracket ''. Instead, '1577' was found on line: 1, column: 1

1577 is the value of the sensors X axis. 
![download](https://user-images.githubusercontent.com/36347204/36599029-0904691a-187c-11e8-86c4-b6f0ddd12dd6.png)

**Comment by iridris** [comment]
This may be related to a known outage on SmartThings related to 3-axis sensors. Details here: https://status.smartthings.com/incidents/vv0w51mwcm85

**Comment by idpaterson** [comment]
Thanks for the outage info, I subscribed for updates to that issue to follow-up once they declare it resolved.

**Comment by staticxsoil** [comment]
Three axis is working properly
