### ISSUE TITLE
You don't have access to ady624/webCoRE

### ISSUE THREAD

**Issue by DeaFroggatt** [ady624/webCoRE#72]
I accidentally deleted the WebCoRE smartApp from Smartthings IDE.  When I went back to try and add it back in through the settings button, I received the subject error message.  I researched through the issues section and noted that a similar issue was resolved by logging out of github and then logging back in.  This did not resolve the issue in my case.
![smartapps1](https://user-images.githubusercontent.com/37716990/45590768-6ffab600-b8f5-11e8-8a49-94989ad12d93.jpg)
![smartapps2](https://user-images.githubusercontent.com/37716990/45590769-74bf6a00-b8f5-11e8-8610-3d60826f805e.jpg)

**Comment by idpaterson** [comment]
Your screenshot shows a possible issue, be sure to use the capitalization webCoRE for the repository name rather than WebCoRE

**Comment by DeaFroggatt** [comment]
I seem to get the same results after revising the repository name.
![smartapps1](https://user-images.githubusercontent.com/37716990/45591116-97558100-b8fd-11e8-82c1-b1fc78d85966.jpg)
![smartapps2](https://user-images.githubusercontent.com/37716990/45591117-9a507180-b8fd-11e8-886d-d122dab05ae1.jpg)

**Comment by DeaFroggatt** [comment]
Sorry, attached wrong screenshots.
![smartapps2](https://user-images.githubusercontent.com/37716990/45591139-25316c00-b8fe-11e8-8901-d4a6cab38e94.jpg)
![smartapps3](https://user-images.githubusercontent.com/37716990/45591142-29f62000-b8fe-11e8-82b7-931e3961f2b5.jpg)

**Comment by idpaterson** [comment]
By logging out of GitHub do you mean that you used the disconnect link on the GitHub popup in SmartThings?

**Comment by DeaFroggatt** [comment]
No, I logged out of my account at GitHub.com and then logged back in.

**Comment by idpaterson** [comment]
Usually when SmartThings cannot connect to GitHub the fix is to use that disconnect link, but since you have quite a few repositories it may be better to wait and try later. Several people have reported the GitHub connection working properly after leaving it alone overnight. The were a lot of issues with GitHub updates last weekend.

**Comment by DeaFroggatt** [comment]
OK, will do.  Thanks for sparing your valuable time assisting me.

**Comment by DeaFroggatt** [comment]
I tried to install WebCoRE again today with the same results.

Out of desperation I decided to install webCoRE manually using Github copy and paste code and creating in Smartthings using the code(s).

All works now, however, my main issue remains that it will be difficult for me to get notices of updates or code changes since I am not using the repository.

**Comment by idpaterson** [comment]
Hopefully the GitHub issue will be resolved eventually. You can subscribe to the Announcements category at community.webCoRE.co for in-depth coverage of each release.

**Comment by CorpulentBrony** [comment]
I'm having the issue as well with a lot of repositories. Is the only known solution either a) do everything manually or b) reset connection and manually re-add all repositories?
