### ISSUE TITLE
timezone update

### ISSUE THREAD

**Issue by gustvao** [ady624/webCoRE#98]
Hello-

Can you pls update the timezone list your application use? I live in Brazil and last quarter it has changed the daylight saving time rules and apparently it is not yet reflected here

more info at
https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/time-zone-updates-for-brazil-are-available/ba-p/751175

**Comment by idpaterson** [comment]
You may be looking for https://community.smartthings.com/

**Comment by gustvao** [comment]
Actually it works if I make use of the smart things app. It is not working with the pistols for webcore.

Can you play verify your Timezone library, apparently you are using an old one in your app or server

**Comment by idpaterson** [comment]
SmartThings provides a time zone library for use by all smart apps running on their Groovy platform. Please post this issue on the SmartThings community forum to bring it to the attention of SmartThings staff and other users who may be affected.
